# Generated by Django 4.2.10 on 2026-05-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_ml_avg_score_alert_ml_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
