# Generated by Django 4.2.10 on 2026-03-16 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'slot_number')},
        ),
        migrations.AddField(
            model_name='facultylecturereminder',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultylecturereminder',
            name='timetable_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetableentry'),
        ),
    ]
