# Generated by Django 4.2.10 on 2026-05-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
