# Generated by Django 4.2.10 on 2026-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgedocument',
            options={},
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='file',
            field=models.FileField(upload_to='knowledge/'),
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
