# Generated by Django 4.2.10 on 2026-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
