# Generated by Django 4.2.10 on 2026-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='courses_assigned',
            field=models.ManyToManyField(blank=True, to='students.course'),
        ),
    ]
